### PR TITLE
Section 4.1

### PR DESCRIPTION
**Pull request by yudetamago**

### CODE REVIEW

**Comment by nrryuya** [comment]
`where func a, b =` or `where func (a, b) =` ?
I prefer the former just because I adopted it already ;)

**Comment by yudetamago** [comment]
>definition fooBar :: A ==> B ==> C is more functional style.

>where func a, b = or where func (a, b) = ?
>I prefer the former just because I adopted it already ;)

Yeah, I think so too.
Original cbc casper paper uses both curried style functions and non-curried ones.

**Comment by nrryuya** [comment]
> Original cbc casper paper uses both curried style functions and non-curried ones.

Ah, right. Then it's better. Let's fix the other definitions later.

**Comment by nrryuya** [comment]
Is there any reason why you skipped some?

**Comment by yudetamago** [comment]
4.7 and 4.9 uses estimator, so it seems not to be done by straightforward way like other definitions, I think...

**Comment by nrryuya** [comment]
>I don't know any idea where to use curried or non-curried ones for now, so I wrote those definitions by the same manner that the paper uses.
>Do you have any idea about this?

By the definition like `SomeFunc: A -> B -> C`, `SomeFunc` don't need to receive B always i.e. you can do `SomeFunc a` which returns a new function typed `B -> C`, basically.

**Comment by yudetamago** [comment]
>By the definition like SomeFunc: A -> B -> C, SomeFunc don't need to receive B always i.e. you can do SomeFunc a which returns a new function typed B -> C, basically.

Yep. My point is whether or not there are the situations that curried style functions are not suitable `in this paper`.

**Comment by nrryuya** [comment]
>Yep. My point is whether or not there are the situations that curried style functions are not suitable in this paper.

It's just because explicit is better I guess?

**Comment by yudetamago** [comment]
>It's just because explicit is better I guess?

Hmm, it seems so.

**Comment by nrryuya** [comment]
Anyway, good catch! Thanks!

**Comment by yudetamago** [comment]
👍

**Comment by yudetamago** [comment]
:merge: !!

**Pull request merged**
